# Generated by Django 5.0.7 on 2024-07-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
    ]
