# Generated by Django 5.0.7 on 2024-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='envio',
            field=models.BooleanField(default=False),
        ),
    ]
